### PR TITLE
Per documentation, allow multiple tags to be specified

### PR DESCRIPTION
**Pull request by leggebroten**

### CODE REVIEW

**Comment by john-doherty** [comment]
Are you able to resolve these @leggebroten?

**Comment by leggebroten** [comment]
Fixed

**Comment by leggebroten** [comment]
Hello?

**Comment by john-doherty** [comment]
Hi :)

**Comment by leggebroten** [comment]
:-)
Curious as to why you're rebasing instead of merging.

**Comment by john-doherty** [comment]
Good point! With no good answer

**Comment by john-doherty** [comment]
Ok, merged. The readme needs updating to reflect this change

**Comment by john-doherty** [comment]
I'm pressed for time at the moment Lee, how about becoming a collaborator? This will give you repo admin access so you can merge, publish etc?

**Comment by leggebroten** [comment]
Thanks John.
I'll update the readme.
I'd be happy to collaborate, though I'll not make any major changes though.  This is your baby.

**Comment by DallasEpperson** [comment]
@leggebroten I can't figure out how to get this to work. I have a test tagged with `@X631` and `@X2257`. If I give `-t @X631` or `-t @X2257`, I can execute those individual tests. But if I want to run them both and I try `-t @X631 -t @X2257`, selenium-cucumber-js exits immediately. What is the proper syntax for specifying multiple tags?

**Pull request merged**
